name: progimage-api-infra-deploy
on:
 push:
   branches:
     - master
   tags:
     - PROGIMAGE-API-PLAY-INFRA-*
   paths:
     - "infra-deploy/**"

jobs:
  progimage-api-infra-play-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@master

      - name: Get the latest terraform version
        run: make terraform-install

      - name: Apply terraform progimage-api infra
        run: make terraform-apply
        working-directory: infra-deploy/
        env:
          TF_IN_AUTOMATION           : true
          TF_WORKSPACE               : play
          AWS_ACCESS_KEY_ID          : ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY      : ${{ secrets.AWS_SECRET_KEY }}
          TF_CLOUD_TOKEN             : ${{ secrets.TF_CLOUD_TOKEN }}
          ENVIRONMENT                : play
